// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUtrkKuBs94PRvmn3SR8j78tDQTjbXx_M',
    appId: '1:1029076770680:web:b15d9821fdbd9991efb28d',
    messagingSenderId: '1029076770680',
    projectId: 'dorm-app15',
    authDomain: 'dorm-app15.firebaseapp.com',
    storageBucket: 'dorm-app15.appspot.com',
    measurementId: 'G-18PYMNFP60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkgFGQxg_NXmSxRer2bE92yBGcv3nTWXU',
    appId: '1:1029076770680:android:8632bb7508c52428efb28d',
    messagingSenderId: '1029076770680',
    projectId: 'dorm-app15',
    storageBucket: 'dorm-app15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbpUoylwPbC9i21AMZrWl-kWrtmWsv3Xw',
    appId: '1:1029076770680:ios:106a286bdda5b5bcefb28d',
    messagingSenderId: '1029076770680',
    projectId: 'dorm-app15',
    storageBucket: 'dorm-app15.appspot.com',
    iosClientId: '1029076770680-o69gbbicq5acrdu2o4jd171t2julr3dj.apps.googleusercontent.com',
    iosBundleId: 'com.palipasoftware.dormApp',
  );
}
